name: docforge
description: DocForge PDF Toolkit
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.2.1
  file_picker: ^8.0.0
  uuid: ^4.2.1
  permission_handler: ^11.3.0
  camera: ^0.10.5
  provider: ^6.1.2
  google_mlkit_document_scanner: ^0.3.0
  google_mlkit_text_recognition: ^0.13.0
  syncfusion_flutter_pdf: ^25.2.7
  pdfx: ^2.9.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  riverpod_annotation: ^2.3.5
  #file_picker: 5.5.0
  #syncfusion_flutter_pdf: ^25.1.35
  #syncfusion_flutter_pdfviewer: ^25.1.35
  #syncfusion_flutter_pdfviewer: ^25.2.7
  path_provider: ^2.1.2
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

